import { useState } from 'react'
import { BRAND } from '../../brand/zylove'
import { CONSENT_IDS, type ConsentId } from '../../services/onboarding'

interface Consent {
  id: ConsentId
  label: string
  details?: string
}

const AGE_CONSENT: Consent = { id: 'age', label: 'I confirm I am at least 18 years of age.' }

const TERMS_CONSENTS: Consent[] = [
  {
    id: 'terms',
    label: 'I agree to the Zylove Terms of Service.',
    details:
      'By agreeing, you accept our full Terms of Service including the binding arbitration clause, class action waiver, and limitation of liability provisions.',
  },
  {
    id: 'privacy',
    label: 'I agree to the Zylove Privacy Policy.',
    details:
      'We collect location, profile data, and behavioral signals to power matching. Your data is never sold. Messages are end-to-end encrypted.',
  },
  {
    id: 'matching',
    label: "I understand how Zylove's matching works.",
    details:
      "Zylove's curated selections and compatibility scores are generated by an algorithm based on data I and other users have voluntarily provided. These scores are not a guarantee of compatibility, chemistry, or relationship success. Zylove is a technology platform, not a professional matchmaking service.",
  },
  {
    id: 'conduct',
    label: "I agree to Zylove's Community Guidelines and will not use the app to harass, scam, or harm others.",
  },
  {
    id: 'safety',
    label:
      'I understand that Zylove cannot guarantee the identity or intentions of other users and I will exercise personal safety precautions.',
  },
]

interface TermsStepProps {
  accepted: boolean
  onAccept: () => Promise<void>
}

export default function TermsStep({ accepted, onAccept }: TermsStepProps) {
  const [checked, setChecked] = useState<Record<ConsentId, boolean>>(() =>
    Object.fromEntries(CONSENT_IDS.map((id) => [id, accepted])) as Record<ConsentId, boolean>,
  )
  const [expanded, setExpanded] = useState<ConsentId | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const allChecked = CONSENT_IDS.every((id) => checked[id])

  async function handleAccept() {
    setSaving(true)
    setError(null)
    try {
      await onAccept()
    } catch {
      setError("Couldn't record your acceptance. Check your connection and try again.")
    } finally {
      setSaving(false)
    }
  }

  function row(c: Consent) {
    return (
      <div key={c.id} className="border-b border-gray-100 py-3 last:border-0">
        <label className="flex cursor-pointer items-start gap-3">
          <input
            type="checkbox"
            checked={checked[c.id]}
            disabled={accepted}
            onChange={(e) => setChecked((s) => ({ ...s, [c.id]: e.target.checked }))}
            className="mt-1 h-5 w-5 shrink-0 accent-gray-900"
          />
          <span className="text-sm leading-relaxed">
            {c.label} <span className="text-red-600">*</span>
          </span>
        </label>
        {c.details && (
          <div className="ml-8">
            <button
              type="button"
              onClick={() => setExpanded(expanded === c.id ? null : c.id)}
              className="mt-1 text-xs font-medium text-gray-600 underline"
            >
              {expanded === c.id ? 'Show less ▲' : 'Read more ▼'}
            </button>
            {expanded === c.id && (
              <p className="mt-2 rounded-lg bg-gray-50 p-3 text-xs leading-relaxed text-gray-600">{c.details}</p>
            )}
          </div>
        )}
      </div>
    )
  }

  return (
    <div>
      <h1 className="mb-1 text-2xl font-semibold">Before you join Zylove</h1>
      <p className="mb-5 text-gray-600">Please read and accept our terms. We've written them to be honest and clear.</p>

      <section className="mb-5 rounded-xl border border-gray-200 p-4">
        <h2 className="mb-1 text-xs font-semibold uppercase tracking-wide text-gray-500">Age requirement</h2>
        {row(AGE_CONSENT)}
      </section>

      <section className="mb-4 rounded-xl border border-gray-200 p-4">
        <h2 className="mb-1 text-xs font-semibold uppercase tracking-wide text-gray-500">Terms</h2>
        {TERMS_CONSENTS.map(row)}
      </section>

      <div className="mb-3 flex flex-wrap gap-x-4 gap-y-1 text-sm font-medium underline">
        <a href={BRAND.termsUrl} target="_blank" rel="noreferrer">Full Terms of Service ↗</a>
        <a href={BRAND.privacyUrl} target="_blank" rel="noreferrer">Privacy Policy ↗</a>
        <a href="https://zylove.app/community" target="_blank" rel="noreferrer">Community Guidelines ↗</a>
      </div>
      <p className="mb-5 text-xs text-gray-500">* All items marked with an asterisk are required.</p>

      {error && <p className="mb-3 text-sm text-red-600">{error}</p>}

      {accepted ? (
        <p className="rounded-lg bg-green-50 p-3 text-center text-sm font-medium text-green-800">✓ Accepted</p>
      ) : (
        <button
          type="button"
          onClick={handleAccept}
          disabled={!allChecked || saving}
          className="w-full rounded-lg bg-gray-900 px-4 py-3 font-medium text-white disabled:opacity-40"
        >
          {saving ? 'Saving…' : 'I agree — continue'}
        </button>
      )}

      <p className="mt-4 text-center text-xs leading-relaxed text-gray-500">
        By tapping "I agree," you confirm you have read and accept all of the above. Your acceptance is logged with a
        timestamp for your protection and ours.
      </p>
    </div>
  )
}
